CREATE  TABLE `movies4us`.`MOVIES_GENRE` (
  `MOVIE_ID` INT NOT NULL COMMENT 'Foreign key from MOVIES table' ,
  `GENRE` VARCHAR(20) NULL COMMENT 'Genres for the movie' ,
  INDEX `MOVIE_ID_FK` (`MOVIE_ID` ASC) )
COMMENT = 'Stores the genre information for each movie';

ALTER TABLE `movies4us`.`MOVIES_GENRE` 
  ADD CONSTRAINT `fk_MOVIES_GENRE_1`
  FOREIGN KEY (`MOVIE_ID` )
  REFERENCES `movies4us`.`MOVIES` (`MOVIE_ID` )
  ON DELETE CASCADE
  ON UPDATE NO ACTION
, DROP INDEX `MOVIE_ID_FK` 
, ADD INDEX `MOVIE_GENRE_INDEX` (`MOVIE_ID` ASC) 
, ADD INDEX `fk_MOVIES_GENRE_1` (`MOVIE_ID` ASC) ;

ALTER TABLE `movies4us`.`MOVIES_GENRE` CHANGE COLUMN `GENRE` `GENRE` VARCHAR(20) NOT NULL COMMENT 'Genres for the movie'  
, ADD PRIMARY KEY (`MOVIE_ID`, `GENRE`) ;