CREATE TABLE `movies4us`.USER_FEATURES(
`USER_ID` INT NOT NULL,
`FEATURE_ID` INT NOT NULL,
`FEATURE_NAME` VARCHAR(50),
`COUNT` INT DEFAULT 0,

PRIMARY KEY(`USER_ID`, `FEATURE_NAME`, FEATURE_ID),
FOREIGN KEY (`USER_ID`) REFERENCES `movies4us`.`USER_INFO` (`USER_ID` )

COMMENT = 'FEATURE_ID ACTOR =1, DIRECTOR=2, LANGUAGE=3';
)